### PR TITLE
Compatibility new FOSUserBundle

### PR DESCRIPTION
**Pull request by Thibault34**
No problem now :)

### CODE REVIEW

**Comment by garak** [comment]
Can you fix failing tests?

**Comment by Thibault34** [comment]
Is php tests ?

**Comment by Thibault34** [comment]
The test falling before

**Comment by Thibault34** [comment]
Hello, can you help me please ?
I don't understand, error is :

> Argument 1 passed to FOS\UserBundle\Doctrine\UserManager::__construct() must be an instance of Symfony\Component\Security\Core\Encoder\EncoderFactoryInterface, instance of Mock_PasswordUpdaterInterface_727bf80d given, called in /home/travis/build/PUGX/PUGXMultiUserBundle/Doctrine/UserManager.php on line 46 and defined

But, EncoderFactoryInterface is no longer in any new version.

**Comment by garak** [comment]
You need to update tests to reflect changes you did in the code

**Comment by Thibault34** [comment]
I have update test.
I don't understand because error is no on PHP 5.5 and more

**Comment by garak** [comment]
The error on 5.3 is about memory, you can ignore it for now. Instead, the problem with 5.4 is tricky, because FOSUserBundle raised its requirements to php 5.5: so it happens that on php 5.4 we get the old version of FOSUserBundle, while on php 5.5 and newer we get the new version of FOSUserBundle. So, we need a solution that fits in both versions of FOSUserBundle, unless we also raise requirements.

**Comment by Thibault34** [comment]
Are you ok for raising requirements ?

**Comment by garak** [comment]
I'm OK. Let's see what others think about it. Ping @leopro @giorrrgio @eux

**Comment by Thibault34** [comment]
I have update test.
I don't understand because error is no on PHP 5.5 and more

**Comment by garak** [comment]
You should also update `.travis.yml` and remove 5.3 and 5.4 builds

**Pull request merged**
