### PR TITLE
Compatibility new FOSUserBundle

### PR DESCRIPTION
**Pull request by Thibault34**

### CODE REVIEW

**Comment by garak** [comment]
Can you resolve conflicts?

**Comment by Thibault34** [comment]
I don't understand wich conflict ? orm.yml ? evrything ok
Can you explain please ?

**Comment by garak** [comment]
It looks like you started your PR before pulling, but this is just a wild guess.

**Comment by Thibault34** [comment]
I can't resolve

**Comment by garak** [comment]
So close this PR and start a new one

**Pull request closed without merging**
