### PR TITLE
Compatibilty new version FriendsOfSymfony/FOSUserBundle

### PR DESCRIPTION
**Pull request by Thibault34**
FriendsOfSymfony/FOSUserBundle has changed this UserManager __construct().

### CODE REVIEW

**Comment by garak** [comment]
Feel free to open a new PR with everything inside, we can't merge two PRs on the same subject

**Comment by Thibault34** [comment]
How to do that please ?
How to add file in a new PR please ?

**Comment by garak** [comment]
https://help.github.com/articles/about-pull-requests/

**Comment by Thibault34** [comment]
I can't add file in my pull request

**Comment by garak** [comment]
This pull request was closed. Open a new pull request

**Pull request closed without merging**
